# Update Newest Midjourney channel‘s image
name: Update Midjourney Image

on:
  # # every 8 minute
  # schedule:
  #   - cron: "8 * * * *"

  # Manual updates
  workflow_dispatch:
    inputs:
      Authorization:
        description: "User Authorization"
        required: true
        default: "Authorization"
      Channel:
        description: "channel 地址"
        required: true
        default: "channel"
      Count:
        description: "爬取个数 max:200"
        required: true
        default: "20"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies
      - name: Install requirements
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Task
        env:
          Channel: ${{github.event.inputs.Channel}}
          Authorization: ${{github.event.inputs.Authorization}}
          Count: ${{github.event.inputs.Count}}

        run: python midjourney.py

      - name: Commit Newest Node
        # Condition to prevent unintended automatic workflow
        # Change or comment out this line for automatic workflow on forks
        if: ${{ github.repository == 'itxve/midjourney-channel-on-github' }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Update README.md" && git push -f || echo "No Change"
